databases:
  - name: croshara-postgres
    plan: free
    region: singapore
    ipAllowList: []

services:
  - type: web
    name: croshara-medusa
    plan: free
    region: singapore
    env: node
    branch: main
    buildCommand: bash build.sh
    startCommand: NODE_OPTIONS="--max-old-space-size=350 --max-semi-space-size=64" node node_modules/@medusajs/cli/cli.js start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: croshara-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STORE_CORS
        value: /https?:\/\/(localhost:3000|localhost:8000|localhost:9000|croshara-.*\.onrender\.com|.*\.vercel\.app)/
      - key: ADMIN_CORS
        value: /https?:\/\/.*croshara-medusa\.onrender\.com/
      - key: AUTH_CORS
        value: /https?:\/\/.*croshara-medusa\.onrender\.com/
      - key: MEDUSA_BACKEND_URL
        value: https://croshara-medusa.onrender.com
      - key: NODE_ENV
        value: production
      - key: MALLOC_ARENA_MAX
        value: "2"
